/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'burtonwynne' at '3/22/16 11:10 PM' with Gradle 2.10
 *
 * @author burtonwynne, @date 3/22/16 11:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
